version: '3.1'
services:
  database:
    image: postgres
    container_name: transaction
    environment:
      - POSTGRES_DB=transaction
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5431:5431"
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    image: app
    expose:
      - 8081
    ports:
      - 8081:8081
      - 8001:8001
    depends_on:
      - database
